version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/joshdk/quantize
    steps:
      - checkout
      - run: sudo env GOOS=darwin GOARCH=amd64 $(which go) install std
      - run: ./godelw version
      - run: ./godelw verify --apply=false
      - run: ./godelw test cover --coverage-output=coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)
      - run: ./godelw dist
